# Generated by Django 4.2.30 on 2026-08-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ingestionfailure',
            name='stage',
            field=models.CharField(choices=[('ncl_download', 'NCL download'), ('ncl_parse', 'NCL parse'), ('google_lookup', 'Google Books lookup'), ('book_upsert', 'Book upsert'), ('cover_storage', 'Cover image storage'), ('ingestion', 'Ingestion run (unclassified)')], max_length=32),
        ),
    ]
